jobs:
  Swift-Format:
    defaults:
      run:
        working-directory: ./ios
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v4
    - continue-on-error: true
      name: Install SwiftFormat
      run: brew install swiftformat
    - continue-on-error: true
      name: Format Swift code
      run: swiftformat --verbose .
    - continue-on-error: true
      name: Verify formatted code is unchanged
      run: git diff --exit-code HEAD
  Swift-Lint:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v4
    - continue-on-error: true
      env:
        WORKING_DIRECTORY: ios
      name: Lint with SwiftLint
      uses: norio-nomura/action-swiftlint@master
      with:
        args: --strict
name: Check iOS
on:
  repository_dispatch:
    types: trigger-ga___check-ios.yml
