jobs:
  JS-Lint:
    name: Lint JS (eslint, prettier)
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v4
    - continue-on-error: true
      name: Install node_modules
      uses: ./.github/actions/setup-node
    - continue-on-error: true
      name: Run ESLint
      run: yarn lint -f @jamesacarr/github-actions
    - continue-on-error: true
      name: Run ESLint with auto-fix
      run: yarn lint --fix
    - continue-on-error: true
      name: Verify no files have changed after auto-fix
      run: git diff --exit-code HEAD
  TypeScript-Check:
    name: Check TS (tsc)
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v4
    - continue-on-error: true
      name: Install node_modules
      uses: ./.github/actions/setup-node
    - continue-on-error: true
      name: Install reviewdog
      uses: reviewdog/action-setup@v1
    - continue-on-error: true
      env:
        REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      name: Check TypeScript
      run: 'yarn tsc | reviewdog -name="tsc" -efm="%f(%l,%c): error TS%n: %m" -reporter="github-pr-review"
        -filter-mode="nofilter" -fail-on-error -tee

        '
name: Check JS
on:
  repository_dispatch:
    types: trigger-ga___check-js.yml
