jobs:
  build-docs:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Checkout
      uses: actions/checkout@v3
    - continue-on-error: true
      name: Setup
      uses: ./.github/actions/setup-bun
      with:
        working-directory: ./docs
    - continue-on-error: true
      name: Cache build
      uses: actions/cache@v3
      with:
        key: ${{ runner.os }}-nextjs-${{ hashFiles('**/bun.lockb') }}-${{ hashFiles('**/package.json')
          }}
        path: 'docs/.next/cache

          '
        restore-keys: '${{ runner.os }}-nextjs-${{ hashFiles(''**/bun.lockb'') }}

          ${{ runner.os }}-nextjs-

          '
    - continue-on-error: true
      name: Build docs
      run: 'bun --cwd docs build

        touch docs/out/.nojekyll'
name: Test Docs build
on:
  repository_dispatch:
    types: trigger-ga___test-build-docs.yml
